pull_request_rules:
  - name: approve dependabot pull requests
    conditions:
      - author=dependabot[bot]
    actions:
      review:
        type: APPROVE
        message: /build

  # - name: comment to start vagrant job
  #   conditions:
  #     - author=dependabot[bot]
  #     - "#approved-reviews-by>=1"
  #   actions:
  #     comment:
  #       message: go vagrant go

  - name: merge dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - "#approved-reviews-by>=1"
      # Must pass codebuild jobs before merge
      - check-success = "build (spel-commercial, amazon-ebssurrogate.minimal-ol-8-hvm)"
      - check-success = "build (spel-commercial, amazon-ebssurrogate.minimal-rhel-8-hvm)"
      - check-success = "build (spel-commercial, amazon-ebssurrogate.minimal-centos-9stream-hvm)"
      - check-success = "build (spel-commercial, amazon-ebssurrogate.minimal-ol-9-hvm)"
      - check-success = "build (spel-commercial, amazon-ebssurrogate.minimal-rhel-9-hvm)"
      - check-success = "build (spel-govcloud, amazon-ebssurrogate.minimal-ol-8-hvm)"
      - check-success = "build (spel-govcloud, amazon-ebssurrogate.minimal-rhel-8-hvm)"
      - check-success = "build (spel-govcloud, amazon-ebssurrogate.minimal-centos-9stream-hvm)"
      - check-success = "build (spel-govcloud, amazon-ebssurrogate.minimal-ol-9-hvm)"
      - check-success = "build (spel-govcloud, amazon-ebssurrogate.minimal-rhel-9-hvm)"
    actions:
      merge:
        method: merge
