name: Run lint and static analyis checks
on:
  pull_request:

concurrency:
  group: lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: plus3it/actions-workflows/.github/workflows/lint.yml@8b6eb1950e584996769b5306ba26a1634b02a38e
    with:
      tardigradelint-target: install/pip_requirements/tests/requirements.txt lint
